version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_apache
      timeout: 300
      runas: root     
 
    
