version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
    
